### ISSUE TITLE
Vision research & implementation

### ISSUE THREAD

**Issue by MojoNojo07** [Team1810Robotics/2023-robot-code#3]
Adding support for the limelight and using the AprilTags for... whatever we're going to use them for.

**Comment by JustJoshingYa** [comment]
Distance measuring for auto? I think that's the main use right now.

**Comment by MojoNojo07** [comment]
Yeah, it would most likely tie into auto climbing. Maybe also for quicker positioning during teleop for scoring, but I don't see that being much of an issue.

**Comment by JustJoshingYa** [comment]
> 
Mr. Tlesis prefers not to take away control from the driver.
